project_url = "https://github.com/cosmos/gaia"

# Settings related to components/sub-modules. Only relevant if you make use of
# components/sub-modules.
[components]

# The title to use for the section of entries not relating to a specific
# component.
general_entries_title = "General"

# The number of spaces to inject before each component-related entry.
entry_indent = 2

    # The components themselves. Each component has a name (used when rendered
    # to Markdown) and a path relative to the project folder (i.e. relative to
    # the parent of the `.changelog` folder).
    [components.all]
    globalfee = { name = "GlobalFee", path = "x/globalfee" }
    tests = { name = "Tests", path = "tests" }
    docs = { name = "Documentation", path = "docs" }