---
project_name: gaia

env:
  - GO111MODULE=on

builds:
  - main: ./cmd/gaiad
    id: "gaiad"
    binary: gaiad
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=netgo ledger
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      # .Env.TM_VERSION is provided in the workflow runner environment -> see .github/workflows/release.yml
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/cosmos/cosmos-sdk/version.Name=gaia -X github.com/cosmos/cosmos-sdk/version.AppName=gaiad -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger -X github.com/tendermint/tendermint/version.TMCoreSemVer={{ .Env.TM_VERSION }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  # disables archiving; to enable use commented lines below
  - format: binary

  # - format: tar.gz
  #   wrap_in_directory: "true"
  #   format_overrides:
  #     - goos: windows
  #       format: zip
  #   name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  #   files:
  #     - LICENSE
  #     - README.md
  #   rlcp: true

release:
  prerelease: true
  name_template: "v{{.Version}}"

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: false
