defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: Automatic merge on approval to the main branch
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}

  - name: Backport patches to the release/v9.1.x branch
    conditions:
      - base=main
      - label=A:backport/v9.1.x
    actions:
      backport:
        branches:
          - release/v9.1.x

  - name: Backport patches to the release/v10.0.x branch
    conditions:
      - base=main
      - label=A:backport/v10.0.x
    actions:
      backport:
        branches:
          - release/v10.0.x

  - name: Backport patches to the release/v11.x branch
    conditions:
      - base=main
      - label=A:backport/v11.x
    actions:
      backport:
        branches:
          - release/v11.x
