// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/lsm/v1beta1/lsm.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TokenizeShareLockStatus indicates whether the address is able to tokenize
// shares
type TokenizeShareLockStatus int32

const (
	// UNSPECIFIED defines an empty tokenize share lock status
	TOKENIZE_SHARE_LOCK_STATUS_UNSPECIFIED TokenizeShareLockStatus = 0
	// LOCKED indicates the account is locked and cannot tokenize shares
	TOKENIZE_SHARE_LOCK_STATUS_LOCKED TokenizeShareLockStatus = 1
	// UNLOCKED indicates the account is unlocked and can tokenize shares
	TOKENIZE_SHARE_LOCK_STATUS_UNLOCKED TokenizeShareLockStatus = 2
	// LOCK_EXPIRING indicates the account is unable to tokenize shares, but
	// will be able to tokenize shortly (after 1 unbonding period)
	TOKENIZE_SHARE_LOCK_STATUS_LOCK_EXPIRING TokenizeShareLockStatus = 3
)

var TokenizeShareLockStatus_name = map[int32]string{
	0: "TOKENIZE_SHARE_LOCK_STATUS_UNSPECIFIED",
	1: "TOKENIZE_SHARE_LOCK_STATUS_LOCKED",
	2: "TOKENIZE_SHARE_LOCK_STATUS_UNLOCKED",
	3: "TOKENIZE_SHARE_LOCK_STATUS_LOCK_EXPIRING",
}

var TokenizeShareLockStatus_value = map[string]int32{
	"TOKENIZE_SHARE_LOCK_STATUS_UNSPECIFIED":   0,
	"TOKENIZE_SHARE_LOCK_STATUS_LOCKED":        1,
	"TOKENIZE_SHARE_LOCK_STATUS_UNLOCKED":      2,
	"TOKENIZE_SHARE_LOCK_STATUS_LOCK_EXPIRING": 3,
}

func (x TokenizeShareLockStatus) String() string {
	return proto.EnumName(TokenizeShareLockStatus_name, int32(x))
}

func (TokenizeShareLockStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1bf8cc0b3b18958, []int{0}
}

// Params defines the parameters for the x/lsm module.
type Params struct {
	// validator_bond_factor is required as a safety check for tokenizing shares
	// and delegations from liquid staking providers
	ValidatorBondFactor cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=validator_bond_factor,json=validatorBondFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"validator_bond_factor" yaml:"validator_bond_factor"`
	// global_liquid_staking_cap represents a cap on the portion of stake that
	// comes from liquid staking providers
	GlobalLiquidStakingCap cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=global_liquid_staking_cap,json=globalLiquidStakingCap,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"global_liquid_staking_cap" yaml:"global_liquid_staking_cap"`
	// validator_liquid_staking_cap represents a cap on the portion of stake that
	// comes from liquid staking providers for a specific validator
	ValidatorLiquidStakingCap cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=validator_liquid_staking_cap,json=validatorLiquidStakingCap,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"validator_liquid_staking_cap" yaml:"validator_liquid_staking_cap"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bf8cc0b3b18958, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// TokenizeShareRecord represents a tokenized delegation
type TokenizeShareRecord struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ModuleAccount string `protobuf:"bytes,3,opt,name=module_account,json=moduleAccount,proto3" json:"module_account,omitempty"`
	Validator     string `protobuf:"bytes,4,opt,name=validator,proto3" json:"validator,omitempty"`
}

func (m *TokenizeShareRecord) Reset()         { *m = TokenizeShareRecord{} }
func (m *TokenizeShareRecord) String() string { return proto.CompactTextString(m) }
func (*TokenizeShareRecord) ProtoMessage()    {}
func (*TokenizeShareRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bf8cc0b3b18958, []int{1}
}
func (m *TokenizeShareRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenizeShareRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenizeShareRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenizeShareRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenizeShareRecord.Merge(m, src)
}
func (m *TokenizeShareRecord) XXX_Size() int {
	return m.Size()
}
func (m *TokenizeShareRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenizeShareRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TokenizeShareRecord proto.InternalMessageInfo

func (m *TokenizeShareRecord) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TokenizeShareRecord) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TokenizeShareRecord) GetModuleAccount() string {
	if m != nil {
		return m.ModuleAccount
	}
	return ""
}

func (m *TokenizeShareRecord) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

// PendingTokenizeShareAuthorizations stores a list of addresses that have their
// tokenize share enablement in progress
type PendingTokenizeShareAuthorizations struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (m *PendingTokenizeShareAuthorizations) Reset()         { *m = PendingTokenizeShareAuthorizations{} }
func (m *PendingTokenizeShareAuthorizations) String() string { return proto.CompactTextString(m) }
func (*PendingTokenizeShareAuthorizations) ProtoMessage()    {}
func (*PendingTokenizeShareAuthorizations) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bf8cc0b3b18958, []int{2}
}
func (m *PendingTokenizeShareAuthorizations) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingTokenizeShareAuthorizations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingTokenizeShareAuthorizations.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingTokenizeShareAuthorizations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingTokenizeShareAuthorizations.Merge(m, src)
}
func (m *PendingTokenizeShareAuthorizations) XXX_Size() int {
	return m.Size()
}
func (m *PendingTokenizeShareAuthorizations) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingTokenizeShareAuthorizations.DiscardUnknown(m)
}

var xxx_messageInfo_PendingTokenizeShareAuthorizations proto.InternalMessageInfo

func (m *PendingTokenizeShareAuthorizations) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// TokenizeShareRecordReward represents the properties of tokenize share
type TokenizeShareRecordReward struct {
	RecordId uint64                                      `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Reward   github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,2,rep,name=reward,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"reward"`
}

func (m *TokenizeShareRecordReward) Reset()         { *m = TokenizeShareRecordReward{} }
func (m *TokenizeShareRecordReward) String() string { return proto.CompactTextString(m) }
func (*TokenizeShareRecordReward) ProtoMessage()    {}
func (*TokenizeShareRecordReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bf8cc0b3b18958, []int{3}
}
func (m *TokenizeShareRecordReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenizeShareRecordReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenizeShareRecordReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenizeShareRecordReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenizeShareRecordReward.Merge(m, src)
}
func (m *TokenizeShareRecordReward) XXX_Size() int {
	return m.Size()
}
func (m *TokenizeShareRecordReward) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenizeShareRecordReward.DiscardUnknown(m)
}

var xxx_messageInfo_TokenizeShareRecordReward proto.InternalMessageInfo

// LiquidValidator is the storage layout for details about a validator's liquid
// stake.
type LiquidValidator struct {
	// operator_address defines the address of the validator's operator; bech
	// encoded in JSON.
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	// Number of shares self bonded from the validator
	ValidatorBondShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=validator_bond_shares,json=validatorBondShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"validator_bond_shares" yaml:"validator_bond_shares"`
	// Number of shares either tokenized or owned by a liquid staking provider
	LiquidShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=liquid_shares,json=liquidShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquid_shares" yaml:"liquid_shares"`
}

func (m *LiquidValidator) Reset()         { *m = LiquidValidator{} }
func (m *LiquidValidator) String() string { return proto.CompactTextString(m) }
func (*LiquidValidator) ProtoMessage()    {}
func (*LiquidValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1bf8cc0b3b18958, []int{4}
}
func (m *LiquidValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidValidator.Merge(m, src)
}
func (m *LiquidValidator) XXX_Size() int {
	return m.Size()
}
func (m *LiquidValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidValidator.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidValidator proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("gaia.lsm.v1beta1.TokenizeShareLockStatus", TokenizeShareLockStatus_name, TokenizeShareLockStatus_value)
	proto.RegisterType((*Params)(nil), "gaia.lsm.v1beta1.Params")
	proto.RegisterType((*TokenizeShareRecord)(nil), "gaia.lsm.v1beta1.TokenizeShareRecord")
	proto.RegisterType((*PendingTokenizeShareAuthorizations)(nil), "gaia.lsm.v1beta1.PendingTokenizeShareAuthorizations")
	proto.RegisterType((*TokenizeShareRecordReward)(nil), "gaia.lsm.v1beta1.TokenizeShareRecordReward")
	proto.RegisterType((*LiquidValidator)(nil), "gaia.lsm.v1beta1.LiquidValidator")
}

func init() { proto.RegisterFile("gaia/lsm/v1beta1/lsm.proto", fileDescriptor_d1bf8cc0b3b18958) }

var fileDescriptor_d1bf8cc0b3b18958 = []byte{
	// 809 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xd8, 0x26, 0xc4, 0x03, 0x6d, 0xdd, 0xa9, 0x81, 0xb5, 0x6b, 0xad, 0xcd, 0x56, 0x05,
	0xcb, 0x10, 0x5b, 0xa5, 0x37, 0xc3, 0xc5, 0x6b, 0xbb, 0x60, 0xd5, 0x4a, 0xad, 0x5d, 0xb7, 0x42,
	0x91, 0xd0, 0x32, 0xde, 0x1d, 0xd6, 0x23, 0x7b, 0x77, 0xcc, 0xce, 0xba, 0x21, 0xfd, 0x00, 0xa8,
	0xea, 0x89, 0x0b, 0x12, 0x27, 0x54, 0x89, 0x0b, 0x42, 0x42, 0xea, 0x21, 0x37, 0xbe, 0x40, 0xb8,
	0x45, 0x39, 0x21, 0x0e, 0x01, 0x25, 0x87, 0x20, 0x8e, 0x7c, 0x02, 0xb4, 0x33, 0x6b, 0x87, 0x24,
	0x26, 0x58, 0xe2, 0x62, 0xcf, 0xbc, 0xf7, 0x9b, 0xdf, 0xfb, 0xbd, 0x7f, 0x0b, 0x0b, 0x2e, 0xa6,
	0xb8, 0x3e, 0xe1, 0x5e, 0xfd, 0xf1, 0x9d, 0x21, 0x09, 0xf1, 0x9d, 0xe8, 0x5c, 0x9b, 0x06, 0x2c,
	0x64, 0x28, 0x1b, 0xf9, 0x6a, 0xd1, 0x3d, 0xf6, 0x15, 0x72, 0x2e, 0x73, 0x99, 0x70, 0xd6, 0xa3,
	0x93, 0xc4, 0x15, 0xae, 0x63, 0x8f, 0xfa, 0xac, 0x2e, 0x7e, 0x63, 0x93, 0x6a, 0x33, 0xee, 0x31,
	0x5e, 0x1f, 0x62, 0x4e, 0x16, 0xcc, 0x36, 0xa3, 0x7e, 0xec, 0xcf, 0x4b, 0xbf, 0x25, 0xb9, 0xe4,
	0x45, 0xba, 0xb4, 0x3f, 0x53, 0x70, 0xad, 0x8f, 0x03, 0xec, 0x71, 0xf4, 0x0c, 0xc0, 0xd7, 0x1e,
	0xe3, 0x09, 0x75, 0x70, 0xc8, 0x02, 0x6b, 0xc8, 0x7c, 0xc7, 0xfa, 0x0c, 0xdb, 0x21, 0x0b, 0x94,
	0x97, 0xcb, 0xa0, 0x92, 0xd1, 0x1f, 0xed, 0x1d, 0x96, 0x12, 0xbf, 0x1e, 0x96, 0x6e, 0x4a, 0x02,
	0xee, 0x8c, 0x6b, 0x94, 0xd5, 0x3d, 0x1c, 0x8e, 0x6a, 0x3d, 0xe2, 0x62, 0x7b, 0xa7, 0x4d, 0xec,
	0xbf, 0x0e, 0x4b, 0xc5, 0x1d, 0xec, 0x4d, 0x1a, 0xda, 0x52, 0x26, 0xed, 0x60, 0x77, 0x03, 0xc6,
	0xf1, 0xdb, 0xc4, 0xfe, 0xfe, 0xe4, 0x45, 0x15, 0x18, 0x37, 0x16, 0x50, 0x9d, 0xf9, 0xce, 0x3d,
	0x01, 0x44, 0x5f, 0x03, 0x98, 0x77, 0x27, 0x6c, 0x88, 0x27, 0xd6, 0x84, 0x7e, 0x3e, 0xa3, 0x8e,
	0xc5, 0x43, 0x3c, 0xa6, 0xbe, 0x6b, 0xd9, 0x78, 0xaa, 0xac, 0x0b, 0x41, 0x5b, 0xab, 0x09, 0x2a,
	0x4b, 0x41, 0xff, 0xca, 0xb6, 0x54, 0xd4, 0xeb, 0x12, 0xde, 0x13, 0x68, 0x53, 0x82, 0x5b, 0x78,
	0x8a, 0xbe, 0x05, 0xb0, 0x78, 0x9a, 0xda, 0x12, 0x69, 0x19, 0x21, 0xed, 0x93, 0xd5, 0xa4, 0xdd,
	0x3a, 0x5f, 0xab, 0x15, 0xd5, 0xe5, 0x17, 0x2f, 0xce, 0x0b, 0x6c, 0x14, 0xfe, 0x78, 0x5e, 0x02,
	0xcf, 0x4e, 0x5e, 0x54, 0xaf, 0x8b, 0x59, 0xfb, 0x42, 0x4c, 0x9b, 0xec, 0xb0, 0xf6, 0x25, 0x80,
	0x37, 0x06, 0x6c, 0x4c, 0x7c, 0xfa, 0x84, 0x98, 0x23, 0x1c, 0x10, 0x83, 0xd8, 0x2c, 0x70, 0xd0,
	0x55, 0x98, 0xa4, 0x8e, 0x02, 0xca, 0xa0, 0x92, 0x36, 0x92, 0xd4, 0x41, 0x39, 0xf8, 0x12, 0xdb,
	0xf6, 0x49, 0xa0, 0x24, 0xa3, 0x64, 0x0c, 0x79, 0x41, 0xb7, 0xe1, 0x55, 0x8f, 0x39, 0xb3, 0x09,
	0xb1, 0xb0, 0x6d, 0xb3, 0x99, 0x1f, 0x2a, 0x29, 0xe1, 0xbe, 0x22, 0xad, 0x4d, 0x69, 0x44, 0x45,
	0x98, 0x59, 0xa8, 0x53, 0xd2, 0x02, 0x71, 0x6a, 0x68, 0xa4, 0x23, 0x79, 0x9a, 0x0e, 0xb5, 0x3e,
	0xf1, 0x1d, 0xea, 0xbb, 0x67, 0xe4, 0x34, 0x67, 0xe1, 0x88, 0x05, 0xf4, 0x09, 0x0e, 0x29, 0xf3,
	0x79, 0xc4, 0x84, 0x1d, 0x27, 0x20, 0x9c, 0x13, 0xae, 0x80, 0x72, 0x2a, 0x62, 0x5a, 0x18, 0xb4,
	0x1f, 0x01, 0xcc, 0x2f, 0x49, 0xc6, 0x20, 0xdb, 0x38, 0x70, 0xd0, 0x4d, 0x98, 0x09, 0xc4, 0xdd,
	0x5a, 0x64, 0xb6, 0x2e, 0x0d, 0x5d, 0x07, 0x51, 0xb8, 0x16, 0x08, 0x98, 0x92, 0x2c, 0xa7, 0x2a,
	0xaf, 0xbc, 0x57, 0xac, 0xc5, 0x05, 0x8e, 0x16, 0x68, 0xbe, 0x7e, 0x51, 0xb5, 0x5b, 0x8c, 0xfa,
	0xfa, 0xdd, 0xa8, 0x97, 0x3f, 0xfc, 0x56, 0x7a, 0xc7, 0xa5, 0xe1, 0x68, 0x36, 0xac, 0xd9, 0xcc,
	0x8b, 0x77, 0x28, 0xfe, 0xdb, 0xe0, 0xce, 0xb8, 0x1e, 0xee, 0x4c, 0x09, 0x9f, 0xbf, 0xe1, 0x46,
	0x1c, 0xa0, 0xb1, 0xfe, 0xf4, 0x79, 0x29, 0xf1, 0x4d, 0x94, 0xf3, 0x4f, 0x49, 0x78, 0x4d, 0x76,
	0xeb, 0xd1, 0xbc, 0x1a, 0xa8, 0x05, 0xb3, 0x6c, 0x4a, 0x02, 0xd1, 0xfa, 0x38, 0x33, 0x21, 0x36,
	0xa3, 0x2b, 0x07, 0xbb, 0x1b, 0xb9, 0x58, 0x55, 0x53, 0x7a, 0xcc, 0x30, 0xa0, 0xbe, 0x6b, 0x5c,
	0x9b, 0xbf, 0x88, 0xcd, 0x68, 0xfb, 0xc2, 0xda, 0xf2, 0xa8, 0x1c, 0x5c, 0x76, 0x4f, 0x6f, 0xfd,
	0x9f, 0xb5, 0x95, 0x4c, 0xda, 0xb9, 0x1d, 0x15, 0xe5, 0xe6, 0xe8, 0x53, 0x78, 0x65, 0x3e, 0xaf,
	0x32, 0xa0, 0x98, 0x07, 0xfd, 0xfd, 0xd5, 0x02, 0xe6, 0x64, 0xc0, 0x33, 0x0c, 0x9a, 0xf1, 0xaa,
	0xbc, 0xcb, 0x08, 0xa7, 0xd5, 0xab, 0xfe, 0x0c, 0xe0, 0x1b, 0x67, 0xba, 0xdd, 0x63, 0xf6, 0xd8,
	0x0c, 0x71, 0x38, 0xe3, 0xa8, 0x0a, 0xdf, 0x1a, 0x3c, 0xb8, 0xdf, 0xd9, 0xec, 0x6e, 0x75, 0x2c,
	0xf3, 0xa3, 0xa6, 0xd1, 0xb1, 0x7a, 0x0f, 0x5a, 0xf7, 0x2d, 0x73, 0xd0, 0x1c, 0x3c, 0x34, 0xad,
	0x87, 0x9b, 0x66, 0xbf, 0xd3, 0xea, 0xde, 0xeb, 0x76, 0xda, 0xd9, 0x04, 0xba, 0x0d, 0xdf, 0xbc,
	0x04, 0x1b, 0x9d, 0x3b, 0xed, 0x2c, 0x40, 0x6f, 0xc3, 0x5b, 0x97, 0x52, 0xc6, 0xc0, 0x24, 0x7a,
	0x17, 0x56, 0xfe, 0x83, 0xcf, 0xea, 0x7c, 0xdc, 0xef, 0x1a, 0xdd, 0xcd, 0x0f, 0xb3, 0xa9, 0x42,
	0xfa, 0xe9, 0x77, 0x6a, 0x42, 0xff, 0x60, 0xef, 0x48, 0x05, 0xfb, 0x47, 0x2a, 0xf8, 0xfd, 0x48,
	0x05, 0x5f, 0x1d, 0xab, 0x89, 0xfd, 0x63, 0x35, 0xf1, 0xcb, 0xb1, 0x9a, 0xd8, 0xd2, 0x2e, 0x8e,
	0xd8, 0x3f, 0xb6, 0x58, 0x8c, 0xd8, 0x70, 0x4d, 0x7c, 0xb8, 0xef, 0xfe, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x24, 0xb8, 0x46, 0x83, 0x4c, 0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ValidatorBondFactor.Equal(that1.ValidatorBondFactor) {
		return false
	}
	if !this.GlobalLiquidStakingCap.Equal(that1.GlobalLiquidStakingCap) {
		return false
	}
	if !this.ValidatorLiquidStakingCap.Equal(that1.ValidatorLiquidStakingCap) {
		return false
	}
	return true
}
func (this *TokenizeShareRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TokenizeShareRecord)
	if !ok {
		that2, ok := that.(TokenizeShareRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.ModuleAccount != that1.ModuleAccount {
		return false
	}
	if this.Validator != that1.Validator {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ValidatorLiquidStakingCap.Size()
		i -= size
		if _, err := m.ValidatorLiquidStakingCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.GlobalLiquidStakingCap.Size()
		i -= size
		if _, err := m.GlobalLiquidStakingCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.ValidatorBondFactor.Size()
		i -= size
		if _, err := m.ValidatorBondFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	return len(dAtA) - i, nil
}

func (m *TokenizeShareRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenizeShareRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenizeShareRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintLsm(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ModuleAccount) > 0 {
		i -= len(m.ModuleAccount)
		copy(dAtA[i:], m.ModuleAccount)
		i = encodeVarintLsm(dAtA, i, uint64(len(m.ModuleAccount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintLsm(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLsm(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PendingTokenizeShareAuthorizations) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingTokenizeShareAuthorizations) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingTokenizeShareAuthorizations) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintLsm(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *TokenizeShareRecordReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenizeShareRecordReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenizeShareRecordReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reward) > 0 {
		for iNdEx := len(m.Reward) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reward[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLsm(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.RecordId != 0 {
		i = encodeVarintLsm(dAtA, i, uint64(m.RecordId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LiquidValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.LiquidShares.Size()
		i -= size
		if _, err := m.LiquidShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.ValidatorBondShares.Size()
		i -= size
		if _, err := m.ValidatorBondShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLsm(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintLsm(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLsm(dAtA []byte, offset int, v uint64) int {
	offset -= sovLsm(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ValidatorBondFactor.Size()
	n += 1 + l + sovLsm(uint64(l))
	l = m.GlobalLiquidStakingCap.Size()
	n += 1 + l + sovLsm(uint64(l))
	l = m.ValidatorLiquidStakingCap.Size()
	n += 1 + l + sovLsm(uint64(l))
	return n
}

func (m *TokenizeShareRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLsm(uint64(m.Id))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovLsm(uint64(l))
	}
	l = len(m.ModuleAccount)
	if l > 0 {
		n += 1 + l + sovLsm(uint64(l))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovLsm(uint64(l))
	}
	return n
}

func (m *PendingTokenizeShareAuthorizations) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovLsm(uint64(l))
		}
	}
	return n
}

func (m *TokenizeShareRecordReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RecordId != 0 {
		n += 1 + sovLsm(uint64(m.RecordId))
	}
	if len(m.Reward) > 0 {
		for _, e := range m.Reward {
			l = e.Size()
			n += 1 + l + sovLsm(uint64(l))
		}
	}
	return n
}

func (m *LiquidValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovLsm(uint64(l))
	}
	l = m.ValidatorBondShares.Size()
	n += 1 + l + sovLsm(uint64(l))
	l = m.LiquidShares.Size()
	n += 1 + l + sovLsm(uint64(l))
	return n
}

func sovLsm(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLsm(x uint64) (n int) {
	return sovLsm(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorBondFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorBondFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalLiquidStakingCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GlobalLiquidStakingCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorLiquidStakingCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorLiquidStakingCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenizeShareRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenizeShareRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenizeShareRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingTokenizeShareAuthorizations) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingTokenizeShareAuthorizations: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingTokenizeShareAuthorizations: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenizeShareRecordReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenizeShareRecordReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenizeShareRecordReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordId", wireType)
			}
			m.RecordId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reward = append(m.Reward, types.DecCoin{})
			if err := m.Reward[len(m.Reward)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLsm
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorBondShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorBondShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLsm
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLsm
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLsm(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLsm
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLsm(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLsm
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLsm
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLsm
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLsm
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLsm
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLsm        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLsm          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLsm = fmt.Errorf("proto: unexpected end of group")
)
