name: Feature Request
description: Create a proposal to request a feature
title: "[Feature]: "
labels: ["type: feature-request", "status: waiting-triage", "admin: epic"]
body:
  - type: markdown
    attributes:
      value: |
       ✰  Thanks for opening an issue! ✰  

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        What are the user needs?
        How could this solution fix the user facing problem? 
      placeholder: Short, concise description of the proposed feature/changes to the repository
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Definition
      description: |
        If applicable please answer the below questions
        Why do we need this feature? 
        What problems may be addressed by introducing this feature?
        What benefits does Gaia stand to gain by including this feature?
        Are there any disadvantages of including this feature?
      placeholder: Description of the issue being faced
    validations:
      required: false

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Feature
      description: |
        Description of the proposed features or changes to an existing feature to meet your needs
      placeholder: Description of the proposed feature(s)
    validations:
      required: true

  - type: textarea
    id: work
    attributes:
      label: Work Breakdown
      description: |
        Break the work into many tasks that will later be turned into issues that can be assigned to developers to work on. 
      placeholder: Description of the steps needed to deliver this feature
      value: | 
        ```[tasklist]
        #### Must have
        - [ ] discuss proposal (if proposal rejected, close EPIC)
        - [ ] create ADR (if ADR rejected, close EPIC)
        - [ ] add sub-tasks needed to implement the proposed feature
        ```

        ```[tasklist]
        #### Nice to have
        - [ ] add sub-tasks that are nice to have for the proposed feature
        ```
    validations:
      required: true
