name: Documentation Request
description: Create an issue for missing or incorrect documentation
title: "[Docs]: "
labels: ["type: docs-req", "status: waiting-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ✰  Thanks for opening an issue! ✰    
        Tell us what you would like to see get added to the documentation or if there is an error in the documentation?

  - type: textarea
    id: what-happened
    attributes:
      label: Summary
      placeholder: Description of what you would like to see
    validations:
      required: true
