package gaia

const (
	appName     = "GaiaApp"
	upgradeName = "v8-Rho"

	// allowed msg types of ica host
	authzMsgExec                                  = "/cosmos.authz.v1beta1.MsgExec"
	authzMsgGrant                                 = "/cosmos.authz.v1beta1.MsgGrant"
	authzMsgRevoke                                = "/cosmos.authz.v1beta1.MsgRevoke"
	bankMsgSend                                   = "/cosmos.bank.v1beta1.MsgSend"
	bankMsgMultiSend                              = "/cosmos.bank.v1beta1.MsgMultiSend"
	distrMsgSetWithdrawAddr                       = "/liquidstaking.distribution.v1beta1.MsgSetWithdrawAddress"
	distrMsgWithdrawValidatorCommission           = "/liquidstaking.distribution.v1beta1.MsgWithdrawValidatorCommission"
	distrMsgFundCommunityPool                     = "/liquidstaking.distribution.v1beta1.MsgFundCommunityPool"
	distrMsgWithdrawDelegatorReward               = "/liquidstaking.distribution.v1beta1.MsgWithdrawDelegatorReward"
	feegrantMsgGrantAllowance                     = "/cosmos.feegrant.v1beta1.MsgGrantAllowance"
	feegrantMsgRevokeAllowance                    = "/cosmos.feegrant.v1beta1.MsgRevokeAllowance"
	govMsgVoteWeighted                            = "/cosmos.gov.v1beta1.MsgVoteWeighted"
	govMsgSubmitProposal                          = "/cosmos.gov.v1beta1.MsgSubmitProposal"
	govMsgDeposit                                 = "/cosmos.gov.v1beta1.MsgDeposit"
	govMsgVote                                    = "/cosmos.gov.v1beta1.MsgVote"
	stakingMsgCreateValidator                     = "/liquidstaking.staking.v1beta1.MsgCreateValidator"
	stakingMsgCreateValidatorResponse             = "/liquidstaking.staking.v1beta1.MsgCreateValidatorResponse"
	stakingMsgEditValidator                       = "/liquidstaking.staking.v1beta1.MsgEditValidator"
	stakingMsgEditValidatorResponse               = "/liquidstaking.staking.v1beta1.MsgEditValidatorResponse"
	stakingMsgDelegate                            = "/liquidstaking.staking.v1beta1.MsgDelegate"
	stakingMsgDelegateResponse                    = "/liquidstaking.staking.v1beta1.MsgDelegateResponse"
	stakingMsgBeginRedelegate                     = "/liquidstaking.staking.v1beta1.MsgBeginRedelegate"
	stakingMsgBeginRedelegateResponse             = "/liquidstaking.staking.v1beta1.MsgBeginRedelegateResponse"
	stakingMsgUndelegate                          = "/liquidstaking.staking.v1beta1.MsgUndelegate"
	stakingMsgUndelegateResponse                  = "/liquidstaking.staking.v1beta1.MsgUndelegateResponse"
	stakingMsgCancelUnbondingDelegation           = "/liquidstaking.staking.v1beta1.MsgCancelUnbondingDelegation"
	stakingMsgCancelUnbondingDelegationResponse   = "/liquidstaking.staking.v1beta1.MsgCancelUnbondingDelegationResponse"
	stakingMsgTokenizeShares                      = "/liquidstaking.staking.v1beta1.MsgTokenizeShares"
	stakingMsgTokenizeSharesResponse              = "/liquidstaking.staking.v1beta1.MsgTokenizeSharesResponse"
	stakingMsgRedeemTokensforShares               = "/liquidstaking.staking.v1beta1.MsgRedeemTokensforShares"
	stakingMsgRedeemTokensforSharesResponse       = "/liquidstaking.staking.v1beta1.MsgRedeemTokensforSharesResponse"
	stakingMsgTransferTokenizeShareRecord         = "/liquidstaking.staking.v1beta1.MsgTransferTokenizeShareRecord"
	stakingMsgTransferTokenizeShareRecordResponse = "/liquidstaking.staking.v1beta1.MsgTransferTokenizeShareRecordResponse"
	stakingMsgExemptDelegation                    = "/liquidstaking.staking.v1beta1.MsgExemptDelegation"
	stakingMsgExemptDelegationResponse            = "/liquidstaking.staking.v1beta1.MsgExemptDelegationResponse"
	vestingMsgCreateVestingAccount                = "/cosmos.vesting.v1beta1.MsgCreateVestingAccount"
	ibcMsgTransfer                                = "/ibc.applications.transfer.v1.MsgTransfer"
	liquidityMsgSwapWithinBatch                   = "/tendermint.liquidity.v1beta1.MsgSwapWithinBatch" //#nosec G101 -- This is a false positive
	liquidityMsgCreatePool                        = "/tendermint.liquidity.v1beta1.MsgCreatePool"
	liquidityMsgDepositWithinBatch                = "/tendermint.liquidity.v1beta1.MsgDepositWithinBatch"
	liquidityMsgWithdrawWithinBatch               = "/tendermint.liquidity.v1beta1.MsgWithdrawWithinBatch"
)
