name: E2E

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: 1.21.0
  TAR_PATH: /tmp/tokenfactory-docker-image.tar
  IMAGE_NAME: tokenfactory-docker-image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: tokenfactory:local
          outputs: type=docker,dest=${{ env.TAR_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}
          path: ${{ env.TAR_PATH }}

  e2e-tests:
    needs: build-docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # names of `make` commands to run tests
        test:
          - "ictest-tokenfactory"
      fail-fast: false

    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: checkout chain
        uses: actions/checkout@v4

      - name: Download Tarball Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}
          path: /tmp

      - name: Load Docker Image
        run: |
          docker image load -i ${{ env.TAR_PATH }}
          docker image ls -a

      - name: Run Test
        run: make ${{ matrix.test }}

  coverage:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4

     - uses: actions/setup-go@v4
       with:
         go-version: ${{ env.GO_VERSION }}

     - name: Download Host Artifact
       uses: actions/download-artifact@v3
       with:
         name: ${{ env.IMAGE_NAME }}
         path: /tmp

     - name: Load Docker Image
       run: |
         docker image load -i ${{ env.TAR_PATH }}
         docker image ls -a

     - name: Run coverage
       run: make coverage

     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v4
       with:
         file: /tmp/tokenfactory-coverage/coverage-merged-filtered.out
         token: ${{ secrets.CODECOV_TOKEN }}
       env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
