{
 "title": "Gaia Metrics",
 "tags": [
  "gaia",
  "cosmos"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Moniker",
    "label": "Moniker",
    "query": {
     "query": "label_values(gaia_begin_blocker_count,moniker)"
    }
   },
   { "name": "Version", "label": "Version", "query": { "query": "label_values(service_version)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "CometBFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Height",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "gaia_cometbft_consensus_height", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Chain Size",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_chain_size_bytes",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Block Processing Time",
     "type": "timeseries",
     "description": "Time spent processing FinalizeBlock",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(gaia_cometbft_state_block_processing_time_bucket[5m]))",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Block Gossip Parts Received Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(gaia_cometbft_consensus_block_gossip_parts_received[5m])\n",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Mempool Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gaia_cometbft_mempool_size_bytes",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Consensus Round Voting Power Percent",
     "type": "timeseries",
     "description": "RoundVotingPowerPercent is the percentage of the total voting power received with a round. The value begins at 0 for each round and approaches 1.0 as additional voting power is observed. The metric is labeled by vote type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_round_voting_power_percent",
       "legendFormat": "{{moniker}}/{{vote_type}}"
      }
     ]
    },
    {
     "title": "Consensus Step Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(gaia_cometbft_consensus_step_duration_seconds_bucket[5m]))\n",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Consensus Round Duration",
     "type": "timeseries",
     "description": "Histogram of round duration.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(gaia_cometbft_consensus_round_duration_seconds_bucket[5m]))\n",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Proposal Create Count",
     "type": "timeseries",
     "description": "ProposalCreationCount is the total number of proposals created by this node since process start. The metric is annotated by the status of the proposal from the application, either 'accepted' or 'rejected'.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "rate(gaia_cometbft_consensus_proposal_create_count[5m])",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Proposal Receive Count",
     "type": "timeseries",
     "description": "ProposalReceiveCount is the total number of proposals received by this node since process start. The metric is annotated by the status of the proposal from the application, either 'accepted' or 'rejected'.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "rate(gaia_cometbft_consensus_proposal_receive_count[5m])",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Quorum Prevote Delay",
     "type": "timeseries",
     "description": "Interval in seconds between the proposal timestamp and the timestamp of the earliest prevote that achieved a quorum.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_quorum_prevote_delay",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Missing Validators",
     "type": "timeseries",
     "description": "Number of validators who did not sign.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_missing_validators",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Byzantine Validator Count",
     "type": "timeseries",
     "description": "Number of validators who tried to double sign.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_byzantine_validators",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Consensus Block Interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(gaia_cometbft_consensus_block_interval_seconds_bucket[5m]))\n",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "Number of Transactions",
     "type": "timeseries",
     "description": "Number of transactions.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_num_txs",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "ABCI Method Timing - Median Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(gaia_cometbft_abci_connection_method_timing_seconds_bucket[5m]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Full Prevote Delay",
     "type": "timeseries",
     "description": "Interval in seconds between the proposal timestamp and the timestamp of the latest prevote in a round where all validators voted.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gaia_cometbft_consensus_full_prevote_delay",
       "legendFormat": "{{moniker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(gaia_process_cpu_seconds_total{moniker=~\"$Moniker\"}[5m]) * 100",
       "legendFormat": "CPU Usage % - {{moniker}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "gaia_go_memstats_heap_alloc_bytes{moniker=~\"$Moniker\"}",
       "legendFormat": "Heap Allocated {{moniker}}"
      },
      {
       "expr": "gaia_go_memstats_heap_inuse_bytes{moniker=~\"$Moniker\"}",
       "legendFormat": "Heap In Use {{moniker}}"
      },
      {
       "expr": "gaia_go_memstats_stack_inuse_bytes{moniker=~\"$Moniker\"}",
       "legendFormat": "Stack In Use {{moniker}}"
      },
      {
       "expr": "gaia_process_resident_memory_bytes{moniker=~\"$Moniker\"}",
       "legendFormat": "Resident Memory {{moniker}}"
      }
     ]
    },
    {
     "title": "Goroutines & Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 394 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "gaia_go_goroutines{moniker=~\"$Moniker\"}",
       "legendFormat": "Goroutines {{moniker}}"
      },
      {
       "expr": "gaia_go_threads{moniker=~\"$Moniker\"}",
       "legendFormat": "OS Threads {{moniker}}"
      }
     ]
    },
    {
     "title": "GC Performance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 394 },
     "targets": [
      {
       "expr": "gaia_runtime_gc_pause_ns{moniker=~\"$Moniker\"}",
       "legendFormat": "GC Pause {{moniker}}"
      },
      {
       "expr": "rate(gaia_runtime_total_gc_pause_ns{moniker=~\"$Moniker\"}[5m])",
       "legendFormat": "GC Pause Rate {{moniker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wasm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open File Descriptors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gaia_process_open_fds{moniker=~\"$Moniker\"}",
       "legendFormat": "{{moniker}}"
      }
     ]
    },
    {
     "title": "WASM Cache Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gaia_wasmvm_cache_size_bytes{moniker=~\"$Moniker\"}",
       "legendFormat": "{{type}} {{moniker}}"
      }
     ]
    },
    {
     "title": "WASM VM Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 379 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "gaia_wasmvm_cache_hits_total{moniker=~\"$Moniker\"}",
       "legendFormat": "Cache Hits {{type}} {{moniker}}"
      },
      {
       "expr": "gaia_wasmvm_cache_misses_total{moniker=~\"$Moniker\"}",
       "legendFormat": "Cache Misses {{moniker}}"
      },
      {
       "expr": "gaia_wasmvm_cache_elements_total{moniker=~\"$Moniker\"}",
       "legendFormat": "Cache Elements {{type}} {{moniker}}"
      }
     ]
    }
   ]
  },
  { "title": "Cosmos SDK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Minted Tokens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaia_minted_tokens{moniker=~\"$Moniker\"}",
     "legendFormat": "Minted Tokens {{moniker}}"
    }
   ]
  },
  {
   "title": "Transaction Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gaia_tx_count{moniker=~\"$Moniker\"}[5m])",
     "legendFormat": "TX Rate - {{moniker}}"
    },
    {
     "expr": "gaia_tx_successful{moniker=\"$Moniker\"}",
     "legendFormat": "Successful TXs - $Moniker"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "description": "Versions used by monikers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (moniker, service_version) (gaia_begin_blocker_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gaia_tx_gas_used{moniker=~\"$Moniker\"}",
     "legendFormat": "Gas Used {{moniker}}"
    },
    {
     "expr": "gaia_tx_gas_wanted{moniker=~\"$Moniker\"}",
     "legendFormat": "Gas Wanted {{moniker}}"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaia_begin_blocker_count{moniker=~\"$Moniker\"}",
     "legendFormat": "Begin Blocker Count {{module}} {{moniker}}"
    },
    {
     "expr": "gaia_end_blocker_count{moniker=~\"$Moniker\"}",
     "legendFormat": "End Blocker Count {{module}} {{moniker}}"
    },
    {
     "expr": "gaia_pre_blocker_count{moniker=~\"$Moniker\"}",
     "legendFormat": "Pre Blocker Count {{module}} {{moniker}}"
    }
   ]
  }
 ]
}