[package]
name = "proto_build"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>", "Christian Borst <christian@althea.systems>"]
edition = "2018"


[dependencies]
prost = "0.10"
tonic = "0.7"
prost-build = "0.10"
walkdir = "2"
regex = "1.5"
tonic-build = "0.7"