// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: microtx/v1/msgs.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgName
// an example Msg for a Tx which is input for the above defined Name service
// NAME
// An example field used as input to the Name service
type MsgName struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgName) Reset()         { *m = MsgName{} }
func (m *MsgName) String() string { return proto.CompactTextString(m) }
func (*MsgName) ProtoMessage()    {}
func (*MsgName) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{0}
}
func (m *MsgName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgName.Merge(m, src)
}
func (m *MsgName) XXX_Size() int {
	return m.Size()
}
func (m *MsgName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgName proto.InternalMessageInfo

func (m *MsgName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgNameResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (m *MsgNameResponse) Reset()         { *m = MsgNameResponse{} }
func (m *MsgNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgNameResponse) ProtoMessage()    {}
func (*MsgNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{1}
}
func (m *MsgNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNameResponse.Merge(m, src)
}
func (m *MsgNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNameResponse proto.InternalMessageInfo

func (m *MsgNameResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgName)(nil), "microtx.v1.MsgName")
	proto.RegisterType((*MsgNameResponse)(nil), "microtx.v1.MsgNameResponse")
}

func init() { proto.RegisterFile("microtx/v1/msgs.proto", fileDescriptor_4ddee508b32d6f4e) }

var fileDescriptor_4ddee508b32d6f4e = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbb, 0x4e, 0xf3, 0x30,
	0x14, 0xc7, 0x9b, 0xef, 0xab, 0xb8, 0x78, 0x01, 0x19, 0x90, 0x4a, 0x00, 0x0b, 0x65, 0x62, 0x69,
	0x8e, 0x52, 0xde, 0x80, 0x99, 0x32, 0x74, 0x83, 0x05, 0x39, 0x91, 0x71, 0x2c, 0xd5, 0x3e, 0x51,
	0xec, 0x46, 0xed, 0xca, 0x13, 0x20, 0xf1, 0x52, 0x8c, 0x95, 0x58, 0x18, 0x51, 0xc2, 0x83, 0xa0,
	0x26, 0x4e, 0x61, 0x60, 0xfb, 0x5f, 0x8e, 0x7e, 0xf6, 0x39, 0xe4, 0x44, 0xab, 0xac, 0x44, 0xb7,
	0x84, 0x2a, 0x01, 0x6d, 0xa5, 0x8d, 0x8b, 0x12, 0x1d, 0x52, 0xe2, 0xe3, 0xb8, 0x4a, 0x42, 0x96,
	0xa1, 0xd5, 0x68, 0x21, 0xe5, 0x56, 0x40, 0x95, 0xa4, 0xc2, 0xf1, 0x04, 0x32, 0x54, 0xa6, 0x9b,
	0x0d, 0x8f, 0x25, 0x4a, 0x6c, 0x25, 0x6c, 0x94, 0x4f, 0xcf, 0x25, 0xa2, 0x9c, 0x0b, 0xe0, 0x85,
	0x02, 0x6e, 0x0c, 0x3a, 0xee, 0x14, 0x1a, 0xcf, 0x0f, 0x4f, 0x7d, 0xdb, 0xba, 0x74, 0xf1, 0x04,
	0xdc, 0xac, 0xfa, 0xaa, 0x7b, 0xee, 0xb1, 0x23, 0x76, 0xa6, 0xab, 0xa2, 0x0b, 0xb2, 0x3b, 0xb5,
	0xf2, 0x8e, 0x6b, 0x41, 0x29, 0x19, 0x1a, 0xae, 0xc5, 0x28, 0xb8, 0x0c, 0xae, 0xf6, 0x67, 0xad,
	0x8e, 0xc6, 0xe4, 0xc0, 0xd7, 0x33, 0x61, 0x0b, 0x34, 0x56, 0xd0, 0x90, 0xec, 0x95, 0x5e, 0xfb,
	0xd1, 0xad, 0x9f, 0xdc, 0x93, 0xff, 0x53, 0x2b, 0xe9, 0x8c, 0x0c, 0x5b, 0xe2, 0x51, 0xfc, 0xb3,
	0x73, 0xec, 0x39, 0xe1, 0xd9, 0x1f, 0x61, 0x0f, 0x8f, 0x46, 0xcf, 0xef, 0x5f, 0xaf, 0xff, 0x68,
	0x74, 0x08, 0xbf, 0x8e, 0xb8, 0xf9, 0xc9, 0xcd, 0xed, 0x5b, 0xcd, 0x82, 0x75, 0xcd, 0x82, 0xcf,
	0x9a, 0x05, 0x2f, 0x0d, 0x1b, 0xac, 0x1b, 0x36, 0xf8, 0x68, 0xd8, 0xe0, 0x61, 0x22, 0x95, 0xcb,
	0x17, 0x69, 0x9c, 0xa1, 0x06, 0x3e, 0x77, 0xb9, 0xe0, 0x63, 0x23, 0x5c, 0x2f, 0xb3, 0x9c, 0x2b,
	0x03, 0xcb, 0x2d, 0xcf, 0xad, 0x0a, 0x61, 0xd3, 0x9d, 0x76, 0xfb, 0xeb, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x3d, 0x2a, 0xfa, 0x6c, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Example service called "Name"
	Name(ctx context.Context, in *MsgName, opts ...grpc.CallOption) (*MsgNameResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Name(ctx context.Context, in *MsgName, opts ...grpc.CallOption) (*MsgNameResponse, error) {
	out := new(MsgNameResponse)
	err := c.cc.Invoke(ctx, "/microtx.v1.Msg/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Example service called "Name"
	Name(context.Context, *MsgName) (*MsgNameResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Name(ctx context.Context, req *MsgName) (*MsgNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microtx.v1.Msg/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Name(ctx, req.(*MsgName))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microtx.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _Msg_Name_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microtx/v1/msgs.proto",
}

func (m *MsgName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Response) > 0 {
		i -= len(m.Response)
		copy(dAtA[i:], m.Response)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Response)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	return n
}

func (m *MsgNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Response)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	return n
}

func sovMsgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgs(x uint64) (n int) {
	return sovMsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Response = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgs = fmt.Errorf("proto: unexpected end of group")
)
