// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: microtx/v1/msgs.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgXfer A Msg meant to send funds from one Althea network wallet to another,
// via an automated device.
// SENDER The account sending funds to receiver, must also be the signer of the
// message
// RECEIVER The account receiving funds from sender
// AMOUNTS The tokens and their quantities which should be transferred
type MsgXfer struct {
	Sender   string       `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string       `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amounts  []types.Coin `protobuf:"bytes,3,rep,name=amounts,proto3" json:"amounts"`
}

func (m *MsgXfer) Reset()         { *m = MsgXfer{} }
func (m *MsgXfer) String() string { return proto.CompactTextString(m) }
func (*MsgXfer) ProtoMessage()    {}
func (*MsgXfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{0}
}
func (m *MsgXfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgXfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgXfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgXfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgXfer.Merge(m, src)
}
func (m *MsgXfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgXfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgXfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgXfer proto.InternalMessageInfo

func (m *MsgXfer) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgXfer) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgXfer) GetAmounts() []types.Coin {
	if m != nil {
		return m.Amounts
	}
	return nil
}

type MsgXferResponse struct {
}

func (m *MsgXferResponse) Reset()         { *m = MsgXferResponse{} }
func (m *MsgXferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgXferResponse) ProtoMessage()    {}
func (*MsgXferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ddee508b32d6f4e, []int{1}
}
func (m *MsgXferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgXferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgXferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgXferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgXferResponse.Merge(m, src)
}
func (m *MsgXferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgXferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgXferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgXferResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgXfer)(nil), "microtx.v1.MsgXfer")
	proto.RegisterType((*MsgXferResponse)(nil), "microtx.v1.MsgXferResponse")
}

func init() { proto.RegisterFile("microtx/v1/msgs.proto", fileDescriptor_4ddee508b32d6f4e) }

var fileDescriptor_4ddee508b32d6f4e = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xbd, 0x4e, 0xeb, 0x30,
	0x14, 0x4e, 0xda, 0xaa, 0xbd, 0xd7, 0x77, 0xb8, 0xf7, 0x86, 0x1f, 0xa5, 0x01, 0x85, 0x2a, 0x53,
	0x17, 0x6c, 0xa5, 0x4c, 0xac, 0x65, 0xa5, 0x4b, 0x26, 0x60, 0x41, 0x4e, 0x70, 0x5d, 0x4b, 0x8d,
	0x4f, 0x14, 0xbb, 0x51, 0xba, 0xf2, 0x04, 0x48, 0xbc, 0x54, 0xc7, 0x4a, 0x2c, 0x4c, 0x08, 0xb5,
	0x3c, 0x08, 0x6a, 0xe2, 0x14, 0x06, 0xb6, 0xef, 0x4f, 0xdf, 0xf1, 0x39, 0x46, 0x47, 0xa9, 0x48,
	0x72, 0xd0, 0x25, 0x29, 0x42, 0x92, 0x2a, 0xae, 0x70, 0x96, 0x83, 0x06, 0x07, 0x19, 0x19, 0x17,
	0xa1, 0xe7, 0x27, 0xa0, 0x52, 0x50, 0x24, 0xa6, 0x8a, 0x91, 0x22, 0x8c, 0x99, 0xa6, 0x21, 0x49,
	0x40, 0xc8, 0x3a, 0xeb, 0x1d, 0x72, 0xe0, 0x50, 0x41, 0xb2, 0x43, 0x46, 0x3d, 0xe5, 0x00, 0x7c,
	0xce, 0x08, 0xcd, 0x04, 0xa1, 0x52, 0x82, 0xa6, 0x5a, 0x80, 0x34, 0xfd, 0x5e, 0xdf, 0xb8, 0x15,
	0x8b, 0x17, 0x53, 0x42, 0xe5, 0xb2, 0xb1, 0xea, 0x71, 0xf7, 0x75, 0x63, 0x4d, 0x6a, 0x2b, 0x28,
	0x51, 0x6f, 0xa2, 0xf8, 0xcd, 0x94, 0xe5, 0xce, 0x31, 0xea, 0x2a, 0x26, 0x1f, 0x58, 0xee, 0xda,
	0x03, 0x7b, 0xf8, 0x3b, 0x32, 0xcc, 0xf1, 0xd0, 0xaf, 0x9c, 0x25, 0x4c, 0x14, 0x2c, 0x77, 0x5b,
	0x95, 0xb3, 0xe7, 0xce, 0x25, 0xea, 0xd1, 0x14, 0x16, 0x52, 0x2b, 0xb7, 0x3d, 0x68, 0x0f, 0xff,
	0x8c, 0xfa, 0xd8, 0xd4, 0xef, 0x56, 0xc3, 0x66, 0x35, 0x7c, 0x05, 0x42, 0x8e, 0x3b, 0xab, 0xb7,
	0x33, 0x2b, 0x6a, 0xf2, 0xc1, 0x7f, 0xf4, 0xd7, 0x4c, 0x8e, 0x98, 0xca, 0x40, 0x2a, 0x36, 0xba,
	0x45, 0xed, 0x89, 0xe2, 0x4e, 0x84, 0x3a, 0xd5, 0x83, 0x0e, 0xf0, 0xd7, 0xc9, 0xb0, 0xc9, 0x7a,
	0x27, 0x3f, 0x88, 0x4d, 0x41, 0xe0, 0x3e, 0xbe, 0x7c, 0x3c, 0xb7, 0x9c, 0xe0, 0x1f, 0xf9, 0xf6,
	0x07, 0xe5, 0x94, 0xe5, 0xe3, 0xeb, 0xd5, 0xc6, 0xb7, 0xd7, 0x1b, 0xdf, 0x7e, 0xdf, 0xf8, 0xf6,
	0xd3, 0xd6, 0xb7, 0xd6, 0x5b, 0xdf, 0x7a, 0xdd, 0xfa, 0xd6, 0xdd, 0x88, 0x0b, 0x3d, 0x5b, 0xc4,
	0x38, 0x81, 0x94, 0xd0, 0xb9, 0x9e, 0x31, 0x7a, 0x2e, 0x99, 0x6e, 0x60, 0x32, 0xa3, 0x42, 0x92,
	0x72, 0xdf, 0xa7, 0x97, 0x19, 0x53, 0x71, 0xb7, 0x3a, 0xde, 0xc5, 0x67, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2b, 0x20, 0x14, 0xae, 0xeb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// The Xfer service is a customizeable version of the bank module's Send
	Xfer(ctx context.Context, in *MsgXfer, opts ...grpc.CallOption) (*MsgXferResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Xfer(ctx context.Context, in *MsgXfer, opts ...grpc.CallOption) (*MsgXferResponse, error) {
	out := new(MsgXferResponse)
	err := c.cc.Invoke(ctx, "/microtx.v1.Msg/Xfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// The Xfer service is a customizeable version of the bank module's Send
	Xfer(context.Context, *MsgXfer) (*MsgXferResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Xfer(ctx context.Context, req *MsgXfer) (*MsgXferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Xfer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Xfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgXfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Xfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/microtx.v1.Msg/Xfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Xfer(ctx, req.(*MsgXfer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "microtx.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Xfer",
			Handler:    _Msg_Xfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microtx/v1/msgs.proto",
}

func (m *MsgXfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgXfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgXfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amounts) > 0 {
		for iNdEx := len(m.Amounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMsgs(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMsgs(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgXferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgXferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgXferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintMsgs(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgs(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgXfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovMsgs(uint64(l))
	}
	if len(m.Amounts) > 0 {
		for _, e := range m.Amounts {
			l = e.Size()
			n += 1 + l + sovMsgs(uint64(l))
		}
	}
	return n
}

func (m *MsgXferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovMsgs(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgs(x uint64) (n int) {
	return sovMsgs(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgXfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgXfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgXfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgs
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgs
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amounts = append(m.Amounts, types.Coin{})
			if err := m.Amounts[len(m.Amounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgXferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgXferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgXferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsgs(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsgs
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgs(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgs
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgs
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgs
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgs
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgs
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgs        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgs          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgs = fmt.Errorf("proto: unexpected end of group")
)
