[package]
name = "ethereum-light-client"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[features]
test-utils = ["dep:milagro_bls"]

[[bin]]
name = "generate_json_schema"
path = "src/bin/generate_json_schema.rs"

[dependencies]
ethereum-trie-db = { workspace = true }
ethereum-types = { workspace = true }

alloy-primitives = { workspace = true, features = ["serde", "hex-compat"] }
alloy-trie = { workspace = true }
alloy-rlp = { workspace = true, features = ["arrayvec"] }
tree_hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
schemars = { workspace = true }
hex = { workspace = true }

# Only used for test-utils feature
milagro_bls = { workspace = true, optional = true }
