#![doc = include_str!("../README.md")]
#![deny(clippy::nursery, clippy::pedantic, warnings, missing_docs)]

/// Defines the API for the server generated by tonic.
#[allow(clippy::nursery, clippy::pedantic)]
pub mod api {
    tonic::include_proto!("relayer");
}

pub mod cli;
pub mod core;
pub mod modules;
