swagger: '2.0'
info:
  title: Cosmoshub - gRPC Gateway docs
  description: A REST interface for state queries
  version: 1.0.0
paths:
  /gaia/globalfee/v1beta1/minimum_gas_prices:
    get:
      operationId: MinimumGasPrices
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              minimum_gas_prices:
                type: array
                items:
                  type: object
                  properties:
                    denom:
                      type: string
                    amount:
                      type: string
                  description: >-
                    DecCoin defines a token with a denomination and a decimal
                    amount.


                    NOTE: The amount field is an Dec which implements the custom
                    method

                    signatures required by gogoproto.
            description: |-
              QueryMinimumGasPricesResponse is the response type for the
              Query/MinimumGasPrices RPC method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      tags:
        - Query
definitions:
  cosmos.base.v1beta1.DecCoin:
    type: object
    properties:
      denom:
        type: string
      amount:
        type: string
    description: |-
      DecCoin defines a token with a denomination and a decimal amount.

      NOTE: The amount field is an Dec which implements the custom method
      signatures required by gogoproto.
  gaia.globalfee.v1beta1.QueryMinimumGasPricesResponse:
    type: object
    properties:
      minimum_gas_prices:
        type: array
        items:
          type: object
          properties:
            denom:
              type: string
            amount:
              type: string
          description: |-
            DecCoin defines a token with a denomination and a decimal amount.

            NOTE: The amount field is an Dec which implements the custom method
            signatures required by gogoproto.
    description: |-
      QueryMinimumGasPricesResponse is the response type for the
      Query/MinimumGasPrices RPC method.
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
