name: Build Against Cosmos-SDK master
on: [pull_request]
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  build-vs-cosmos-sdk-master:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-tests')"
    steps:
      - uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.14
      - name: Setup env for GO
        #  this is only used until the setup-go action is updated
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - uses: actions/checkout@v2
      - name: Patch modules
        run: |
          for ext in mod sum; do cp -v go.${ext} go.${ext}.bak ; done
          go get github.com/cosmos/cosmos-sdk@master ; go mod tidy
      - name: Build if changes are detected
        run: |
          trap 'for ext in mod sum; do mv -v go.${ext}.bak go.${ext} ; done' EXIT
          if diff -u go.mod.bak go.mod ; then
            echo This revision requires no changes to build against github.com/cosmos/cosmos-sdk@master
            exit 0
          fi
          make build
