name: Publish Docker image
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
  push: 
  release:
    types: [published, created, edited]

      
jobs:
  push_to_registry:
    name: Push Multiplatform Gaia Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.1.0

      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
          echo $GITHUB_REPOSITORY
          
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Packages Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
# https://github.com/docker/build-push-action/issues/205
# https://github.com/docker/build-push-action/issues/127
# Sidestepping by manually calling docker buildx build --load and then in the next step, pushing
# When Github allows logins to ghc via secrets.GITHUB_TOKEN, instead of requiring a new PAT, it makes sense to switch over to ghcr. 
# They estimate halfway through March: https://github.community/t/how-to-use-installation-access-token-in-ghcr-io-authorization/130666/17

      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64,linux/arm64 --load --tag docker.pkg.github.com/${{ github.REPOSITORY }}:${{ github.SHA }} .

      - name: Push Docker Image
        run: docker push docker.pkg.github.com/${{ github.REPOSITORY }}:${{ github.SHA }}

