name: Publish Docker image
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
  push: 
  release:
    types: 
      - created
      
jobs:
  push_to_registry:
    name: Push Multiplatform Gaia Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.1.0

      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
          echo $GITHUB_REPOSITORY
          
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Packages Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.REPOSITORY }}:${{ env.CI_REF_NAME }},${{ github.REPOSITORY }}:${{ env.CI_REF_NAME }}
