# This is an attempt to build gaia for many OSes and instruction set architectures at once.
# The ARM64 binaries this process will produce will reduce the size of gaia-pi.img by several gigabytes.

name: Gaia Matrix
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        arch: [amd64, arm64, risc64]
        targetos: [windows, darwin, linux]
    name: Gaia ${{ matrix.arch }} for ${{ matrix.targetos }} 
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env: 
          GOOS: ${{ matrix.buildOS }}
          GOARCH: ${{ matrix.arch }}
      - name: Test
        run: make test test-all
      - name: Compile
      - run: make build
      - uses: actions/upload-artifact@v2
        with:
          name: gaia ${{ matrix.buildos }} ${{ matrix.arch }}
          path: build
            
      
      
# name: Cache Go modules
#  uses: actions/cache@preview
#  with:
#    path: ~/go/pkg/mod
#    key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
#		restore-keys: |
#      ${{ runner.OS }}-build-${{ env.cache-name }}-
#      ${{ runner.OS }}-build-
#      ${{ runner.OS }}-
