# This is an attempt to build gaia for many OSes and instruction set architectures at once.
# The ARM64 binaries this process will produce will reduce the size of gaia-pi.img by several gigabytes.

name: Gaia Matrix
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix: 
        arch: [amd64, arm64, risc64]
        targetos: [windows, darwin, linux]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Gaia ${{ matrix.os }} for ${{ matrix.targetos }} ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env: |
          GOOS: ${{ matrix.buildOS }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
      - run: make build
            
      
      
# name: Cache Go modules
#  uses: actions/cache@preview
#  with:
#    path: ~/go/pkg/mod
#    key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
#		restore-keys: |
#      ${{ runner.OS }}-build-${{ env.cache-name }}-
#      ${{ runner.OS }}-build-
#      ${{ runner.OS }}-
