name: Check Markdown links
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          folder-path: "docs"
          file-extension: ".mdx"