name: End to End testing relayer
on:
  pull_request:
  push:
    branches: master
    
env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  test-end-to-end-relayer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
      - run: cp ./target/debug/hermes .
      - name: Build relayer image
        run: docker-compose -f ci/docker-compose-gaia-future.yml build relayer
      - name: Start chains and relayer
        run: docker-compose -f ci/docker-compose-gaia-future.yml up -d ibc-0 ibc-1 relayer
      - name: Run relayer workflow
        continue-on-error: false
        run: docker exec relayer /bin/sh -c /relayer/e2e.sh
