name: Generate Completion script
on:
  pull_request:
    branches:
      - "rc**"

jobs:
  build_and_generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          make build
      - name: generate completion script
        run: |
          ./build/gaiad completion > ../shell_completion/_gaiad
