name: Standup
# Stands up a node in Github actions, using the instant gratification snippet, to verify that it works at all times. 
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - name: Snippet
        run: |
          git clone -b v4.0.4 https://github.com/cosmos/gaia
          cd gaia
          make install
          gaiad init thisnodeisinci
          wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
          gzip -d genesis.cosmoshub-4.json.gz
          mv genesis.cosmoshub-4.json ~/.gaia/config/genesis.json
          gaiad start --p2p.seeds bf8328b66dceb4987e5cd94430af66045e59899f@public-seed.cosmos.vitwit.com:26656,cfd785a4224c7940e9a10f6c1ab24c343e923bec@164.68.107.188:26656,d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656,ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656,3c7cad4154967a294b3ba1cc752e40e8779640ad@84.201.128.115:26656 --x-crisis-skip-assert-invariants
