
name: State Sync
on:
  pull_request:
  push:
    branches:
      - main
      
      
jobs:
  statesync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: State Sync
        run: bash contrib/statesync.bash
        
