name: Static Check
on: [push, pull_request]


jobs:
- name: Staticcheck
  run: |
    # add executables installed with go get to PATH
    # TODO: this will hopefully be fixed by
    # https://github.com/actions/setup-go/issues/14
    export PATH=${PATH}:`go env GOPATH`/bin
    go get -u honnef.co/go/tools/cmd/staticcheck
    staticcheck ./...
